# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "Daniel Livingston"
languageCode = "en-us"
baseURL = "https://www.daniel-livingston.com/"
copyright = "© {year} Daniel Livingston"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"
  buildStatus = "https://app.netlify.com/sites/www-livingston/deploys"
  resumeSRC = "https://github.com/daniellivingston/resume"
  resumePDF = "https://github.com/daniellivingston/resume/raw/pdf/livingston_daniel_resume.pdf"
  resumeHTML = "https://daniellivingston.github.io/resume/"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  instagram = "https://instagram.com/liv.ing.ston"
  linkedin = "https://www.linkedin.com/in/danielrlivingston/"
  github = "https://github.com/daniellivingston"
  email = "mailto:daniel.livingston@live.com"

  # twitter = "https://twitter.com/<your handle>"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", 
  #   "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "Email", "LinkedIn", "Instagram"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "🏡 home"
  title = "Home"
  url = "/"

#[[menu.main]]
#  identifier = "blog"
#  name = "📝 blog"
#  title = "Blog"
#  url = "/blog"

[[menu.main]]
  identifier = "about"
  name = "🙋‍♂️ about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "resume"
  name = "📄 résumé"
  title = "Résumé"
  url = "/resume"

[[menu.main]]
  identifier = "projects"
  name = "🛠 projects"
  title = "Projects"
  url = "/projects"
